version: '3.8'

# Services
services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    command: bash -c "python weather_project/manage.py migrate && python weather_project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - '8000:8000'
    env_file: ./server/.env
    depends_on:
      - db

  # Client service ...
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    stdin_open: true
    # Live reload
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '8080:8080'
    volumes:
      - './client/:/usr/src/app:delegated'
      - /usr/src/app/node_modules/
    depends_on:
      - server

  # Database service
  db:
    image: postgres:15
    container_name: postgres_server
    env_file: ./server/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
