# Generated by Django 5.0.6 on 2024-05-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_api", "0002_note_delete_appuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Note",
        ),
    ]
