name: Django CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.2]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: server
      - name: Run Tests
        run: |
          python manage.py test
        working-directory: server/weather_project
      # - name: Linting with Pylint
      #   run: |
      #     pylint *
      #   working-directory: server/weather_project
      - name: Coverage report
        run: |
          coverage run manage.py test
          coverage report
        working-directory: server/weather_project
